### ISSUE TITLE
VASP Setup

### ISSUE THREAD

**Issue by Bismarrck** [materialsvirtuallab/snap#1]
Hi, I met some problem reproducing the VASP result for a Ni slab.

The total energy difference is significant. I hope you can help me figuring out what should be changed.

* Your energy is -33.38981773 eV
* Mine is around -31.66 eV
[results.zip](https://github.com/materialsvirtuallab/snap/files/2810736/results.zip)

This is the JSON dict, the 4th item of [Ni/Surface.json](https://github.com/materialsvirtuallab/snap/blob/b3cb1519a8940961578ae2c9c93e55a4348e160e/Ni/training/Surface.json#L1):

```python
{'_id': '59b4ba43ffc31d171c78afbb',
 'params': {'pp': {'Ni': 'Ni_pv'},
  'env': 'bulk',
  'e_cut': 520,
  'k_prod': 40,
  'bader': False},
 'group': 'Ni',
 'tags': ['Surface'],
 'structure': {'@module': 'pymatgen.core.structure',
  '@class': 'Structure',
  'lattice': {'matrix': [[2.479787, 0.0, 0.0],
    [-1.239893, 2.147558, 0.0],
    [0.0, 0.0, 24.294656]],
   'a': 2.479787,
   'b': 2.479786284100507,
   'c': 24.294656,
   'alpha': 90.0,
   'beta': 90.0,
   'gamma': 119.99999621016981,
   'volume': 129.38086036717198},
  'sites': [{'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.333334, 0.666668, 0.082544],
    'xyz': [3.3333399995783e-07, 1.4317081967440002, 2.005378084864],
    'label': 'Ni'},
   {'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.0, 0.0, 0.999689],
    'xyz': [0.0, 0.0, 24.287100361984002],
    'label': 'Ni'},
   {'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.666666, 0.333332, 0.166332],
    'xyz': [1.2398936666659999, 0.7158498032560001, 4.040978721792],
    'label': 'Ni'},
   {'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.333334, 0.666668, 0.334122],
    'xyz': [3.3333399995783e-07, 1.4317081967440002, 8.117379052032],
    'label': 'Ni'},
   {'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.0, 0.0, 0.250335],
    'xyz': [0.0, 0.0, 6.081802709759999],
    'label': 'Ni'},
   {'species': [{'element': 'Ni', 'occu': 1}],
    'abc': [0.666666, 0.333332, 0.416978],
    'xyz': [1.2398936666659999, 0.7158498032560001, 10.130337069568],
    'label': 'Ni'}]},
 'num_atoms': 6,
 'outputs': {'energy': -33.38981773,
  'forces': [[-0.0, -0.0, -0.00470706],
   [0.0, 0.0, 0.00549928],
   [0.0, -0.0, -0.00421769],
   [0.0, 0.0, 0.00470706],
   [-0.0, 0.0, 0.00421769],
   [-0.0, -0.0, -0.00549928]],
  'stress': [-22.25152803, -22.25151688, -14.67323629, -5.18e-06, 0.0, 0.0]}}
```

Here is my INCAR (generated by `pymatgen.io.vasp.sets.MVLSlabSet`):

```
ALGO = Fast
EDIFF = 0.0001
EDIFFG = -0.02
ENCUT = 520
IBRION = 2
ICHARG = 1
ISIF = 3
ISMEAR = 0
ISPIN = 2
LORBIT = 11
LREAL = Auto
LWAVE = False
MAGMOM = 6*5.0
NELM = 100
NSW = 99
PREC = Accurate
SIGMA = 0.05
```

* VASP: 5.4.4
* POTCAR: potpaw_PBE/Ni_pv/POTCAR
* Other files are included in **results.zip**

**Comment by Bismarrck** [comment]
@ucsdlxg

**Comment by ucsdlxg** [comment]
There are warnings in your output. Try to use LREAL=False, and ISMEAR=-5 in INCAR.

**Comment by Bismarrck** [comment]
@ucsdlxg 

Hi, I still cannot reproduce the total energy result.
[New VASP calculation files](https://github.com/materialsvirtuallab/snap/files/2863052/single-point.zip) are attached.

This time I set `ISMEAR=0`, `LREAL=False` and `Sigma=0.05`

```
ALGO = Fast
EDIFF = 0.00001
EDIFFG = -0.02
IBRION = -1
ENCUT = 520
ICHARG = 1
ISIF = 2
ISMEAR = 0
ISPIN = 2
LREAL = .FALSE.
LWAVE = .FALSE.
MAGMOM = 6*5.0
NSW = 0
NELM = 99
PREC = Accurate
SIGMA = 0.05
```

No warning found in `OUTCAR`.

However, the total energy difference is still around 2 eV.

Could you please help me check this?

**Comment by ucsdlxg** [comment]
You can increase your k-mesh in x,y. But for z direction, why use 2? It is vacuum, not periodic, use 1 instead. The absolute value is not very meaningful. You need to check the formation energy.
Hope this helps.

**Comment by Bismarrck** [comment]
@ucsdlxg 

I did a new calculation with k-points **40 40 1** and the free energy `TOTEN` is around -31.64 eV. Still significantly differs from your result.

```json
{
'outputs': {'energy': -33.38981773,
  'forces': [[-0.0, -0.0, -0.00470706],
   [0.0, 0.0, 0.00549928],
   [0.0, -0.0, -0.00421769],
   [0.0, 0.0, 0.00470706],
   [-0.0, 0.0, 0.00421769],
   [-0.0, -0.0, -0.00549928]],
  'stress': [-22.25152803, -22.25151688, -14.67323629, -5.18e-06, 0.0, 0.0]}
}
```

Does the `energy` in your JSON files means the free energy `TOTEN`?

```
free energy    TOTEN  =       -31.40128926 eV
```

If so, I believe these values should be equal as the VASP settings are (almost) identical.

**Comment by shyuep** [comment]
@ucsdlxg I don't think a 2eV difference is caused by mere convergence issues. It might actually be the psuedopotential version. Or maybe the energy definition (without entropy, with entropy, etc.)

**Comment by Bismarrck** [comment]
@shyuep 

My POTCAR is PAW ``Ni_pv`` (Sep 06, 2000).

```
  PAW_PBE Ni_pv 06Sep2000                
   16.0000000000000     
 parameters from PSCTR are:
   VRHFIN =Ni:
   LEXCH  = PE
   EATOM  =  3501.1230 eV,  257.3253 Ry

   TITEL  = PAW_PBE Ni_pv 06Sep2000
   LULTRA =        F    use ultrasoft PP ?
   IUNSCR =        1    unscreen: 0-lin 1-nonlin 2-no
   RPACOR =    1.500    partial core radius
   POMASS =   58.690; ZVAL   =   16.000    mass and valenz
   RCORE  =    2.000    outmost cutoff radius
   RWIGS  =    2.000; RWIGS  =    1.058    wigner-seitz radius (au A)
   ENMAX  =  367.986; ENMIN  =  275.989 eV
   RCLOC  =    1.301    cutoff for local pot
   LCOR   =        T    correct aug charges
   LPAW   =        T    paw PP
   EAUG   =  703.443
   DEXC   =    0.000
   RMAX   =    2.041    core radius for proj-oper
   RAUG   =    1.300    factor for augmentation sphere
   RDEP   =    2.103    radius for radial grids
   RDEPT  =    1.618    core radius for aug-charge
```

**Comment by ucsdlxg** [comment]
@shyuep , even the entropy is not that big. I suspect the reference energy is not the same, e.g. the potential version. That's why I said the absolute value is not meaningful, should check the formation energy.

For the POTCAR, I do find the difference...even they seem to be the same version.
My POTCAR first few lines are as follows, the EATOM differs a lot.

PAW_PBE Ni_pv 06Sep2000
 16.0000000000000000
 parameters from PSCTR are:
   VRHFIN =Ni:
   LEXCH  = PE
   EATOM  =  3500.3496 eV,  257.2684 Ry

**Comment by Bismarrck** [comment]
@ucsdlxg 

Interesting. 

I will contact my admin to get a new copy of PAW potentials to see if there is something wrong.

**Comment by Bismarrck** [comment]
@ucsdlxg @shyuep 

Finally the problem is solved.

I got a VASP PAW_PBE_2007 potential set from a colleague. 
The `Ni_pv/POTCAR` is identical to yours. 
I just successfully reproduced your total energy result.

Here is the POTCAR: [Ni_pv2007](https://github.com/materialsvirtuallab/snap/files/2863470/POTCAR.2007.txt)
