### ISSUE TITLE
MAE of Snap/Mo and EAM/Zhou04

### ISSUE THREAD

**Issue by Bismarrck** [materialsvirtuallab/snap#2]
Hi,

From your [Snap/Mo](https://link.aps.org/doi/10.1103/PhysRevMaterials.1.043603) paper:

> In comparison, the corresponding MAEs in the energies, forces, and stress components for the Mo EAM potential of Zhou et al. [32] are 122 meV/atom, 0.41 eV/A° , and 3.48 GPa, respectively

However, I find that the direct total energy MAE (**~4 eV/atom**) of the absolute EAM/Zhou04 and DFT is far larger than 122 meV/atom.

But the relative total energy MAE is around this value:

```python
y_eam = array_of_eam_energies / array_of_natoms - eam_bulk
y_dft = array_of_dft_energies / array_of_natoms - dft_bulk
print(mean_absolute_error(y_eam, y_dft)
```

Is my guess correct?

## Example

The total energy of the last structure of [Mo.surface.json](
https://github.com/materialsvirtuallab/snap/blob/master/Mo/training/Surface.json):

```python
dft_energy = -10.3133037725 * 12
```

The DFT total energy of bulk bcc Mo is around `-10.91973776 eV`
The EAM/Zhou04 total energy of this structure is just `-75.384721 eV`
The EAM/Zhou04 total energy of bulk bcc Mo is `-6.8100034 eV`

```python
y_dft = -123.75964527
dft_ref = -10.91973776
y_eam = -75.384721
eam_ref = -6.8100034
print(y_dft / 12 - dft_ref - (y_eam / 12 - eam_ref)) # 0.07849067083333416
```

So the direct diff is `4.03124 eV/atom` while the relative diff is `0.078 eV/atom`.

**Comment by Bismarrck** [comment]
@chc273

**Comment by Bismarrck** [comment]
Here is the Mo zhou04 potential file created by Zhou's fortran code.

[Mo.set.txt](https://github.com/materialsvirtuallab/snap/files/2882659/Mo.set.txt)

**Comment by chc273** [comment]
@Bismarrck The short answer is yes. We subtracted the constant shift when comparing the energies.
